### ISSUE TITLE
Additional usage: flow style comment

### ISSUE THREAD

**Issue by mattphillips** [kentcdodds/babel-plugin-preval#2]
Hey cool project! :smile:

I was thinking another usage could be to have flow (`// @flow`) style comments at the start of a file to be ran through `preval`. 

That way the consumer of a file would not need to annotate an import. Instead a module would have the scope defined to be pre-evaluated, without the need to explicitly import `babel-plugin-preval`.

Example:

foo.js
```js
// @preval
const fs = require('fs');
module.exports = fs.readFileSync(require.resolve('./foo.txt'), 'utf8');

//      ↓ ↓ ↓ ↓ ↓ ↓
module.exports = "Hello world!"
```

bar.js
```js
const foo = require('./foo');

console.log(foo); // Hello world!
```

**Comment by kentcdodds** [comment]
Ah, yeah, very interesting! I think I love it! I can't help but feel like there could be some edge case or confusion that I'm not considering. I'm going to ask others to weigh in. Thanks!

**Comment by kentcdodds** [comment]
Ah, you know what, there's a pretty bad show-stopper issue here and that is that this would require that the babel plugin would have to read all of the files referenced by every import/require statement in order to know whether it needed to be prevaled. This would result in really terrible performance. I don't think that we can do that. :-(

**Comment by kentcdodds** [comment]
What we could do though is only apply this to the source files (so the ones with the comment). So, if there's a `// @preval` comment at the top of the file, then we run the file and replace the `module.exports` with the final version of the file. This would work well I think.... 🤔

**Comment by mattphillips** [comment]
I think that could work. I'm new to babel plugins but am happy to help get this working what would be the best thing to start looking at?

**Comment by kentcdodds** [comment]
Sure, I just added [this test case](https://github.com/kentcdodds/babel-plugin-preval/blob/6e50a615fad78f59ce2384a840c129040ae521a1/src/__tests__/index.js#L104-L115). Follow [the instructions for contributing](https://github.com/kentcdodds/babel-plugin-preval/blob/6e50a615fad78f59ce2384a840c129040ae521a1/CONTRIBUTING.md), run `npm start test.watch`, change `skip: true` to `only: true` and make that test pass.

[This might help](https://www.youtube.com/watch?v=CFQBHy8RCpg) 😄

**Comment by mattphillips** [comment]
Nice one lets see how I get on :wink:

**Comment by kentcdodds** [comment]
Supported!
