### ISSUE TITLE
Cannot read property 'leadingComments' of undefined

### ISSUE THREAD

**Issue by aputinski** [kentcdodds/babel-plugin-preval#20]
- `babel-plugin-preval` version: `1.4.1`
- `node` version: `7.10.0`
- `npm` (or `yarn`) version: `4.2.0`

What you did:

Added an empty entry point to my webpack config (using `babel-loader` and `babel-plugin-preval`)

What happened:

Webpack failed to compile with the following error:
`Cannot read property 'leadingComments' of undefined`

Adding comments to the file does not fix. Adding any JavaScript code to the file fixes the issue.

**Comment by kentcdodds** [comment]
Thanks for reporting this @aputinski! We should probably change [this line](https://github.com/kentcdodds/babel-plugin-preval/blob/635a162c6304152fecb16da6a2baf56209b2613b/src/index.js#L14) to:

```js
const firstNode = path.node.body[0] || {}
const comments = firstNode.leadingComments || []
```

And we should [add a test](https://github.com/kentcdodds/babel-plugin-preval/blob/0e031f6b26ca52ddb914711bf8b4ae65717efc8d/src/__tests__/index.js#L206)

Could you do that please?

**Comment by obartra** [comment]
That change fixes the issue for me as well

**Comment by kentcdodds** [comment]
Cool! Would you like to [make a pull request](http://makeapullrequest.com)?

**Comment by kentcdodds** [comment]
cc @boennemann, not sure whether you subscribed to this issue, but clearly you were interested in it being fixed. @obartra fixed it :smile:

**Comment by boennemann** [comment]
> cc @boennemann, not sure whether you subscribed to this issue, but clearly you were interested in it being fixed. @obartra fixed it 😄

Awesome thanks 👍
