### ISSUE TITLE
Conflict

### ISSUE THREAD

**Issue by pro-nasa** [kentcdodds/babel-plugin-preval#28]
Hi

If we use "babel-plugin-transform-decorators-legacy", there is a conflict, because both plugins must be placed at the top 

decorators ok, preval not ok

`[
  "transform-decorators-legacy",
  "preval"
]`

preval ok, decorators not ok
`[
  "preval",
  "transform-decorators-legacy"
]`

**Comment by kentcdodds** [comment]
Nice catch! Could you add a note about this in the README?
