### ISSUE TITLE
Non-default imports/exports are not working properly

### ISSUE THREAD

**Issue by kripod** [kentcdodds/babel-plugin-preval#32]
- `babel-plugin-preval` version: 1.4.4
- `node` version: 8.4.0
- `yarn` version: 0.27.5

Relevant code or config

```javascript
import { readdirSync } from 'fs';
import { join } from 'path';

const ROMS_PATH = join(__dirname, '../roms');

export const ROM_FILE_EXTENSION = '.ch8';

const ROM_CATEGORIES = ['demos', 'games', 'programs'];

export default ROM_CATEGORIES
  .map(category => [
    category,
    readdirSync(join(ROMS_PATH, category))
      .filter(fileName => fileName.endsWith(ROM_FILE_EXTENSION)) // Keep ROMs only
      .map(fileName => fileName.slice(0, -ROM_FILE_EXTENSION.length)), // Remove file extension
  ]);
```

What you did:

Trying to use non-default ES2015+ exports.

```javascript
import ROMList, { ROM_FILE_EXTENSION  } from /* preval */ './get-list-of-roms';

console.log(ROMList); // Working
console.log(ROM_FILE_EXTENSION); // undefined
```

What happened:

Nothing got assigned to the non-default exported constant's value.

Problem description:

Non-default imports/exports are not working properly when using a `/* preval */` import comment.

**Comment by kentcdodds** [comment]
Hi! Thanks for the issue. As you stated:

> Non-default imports/exports are not working properly when using a /* preval */ import comment.

Non-default imports are not currently supported by preval, but I think that would be neat so I'm happy to review a PR. Feel free to [make a pull request](http://makeapullrequest.com). The code is around [here](https://github.com/kentcdodds/babel-plugin-preval/blob/0590aea20e3bf56beea87ea5a4a90a8306c99c08/src/index.js#L79-L99) and the tests are around [here](https://github.com/kentcdodds/babel-plugin-preval/blob/0590aea20e3bf56beea87ea5a4a90a8306c99c08/src/__tests__/index.js#L41-L83).

Thanks!

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this as it appears to be stale. Anyone can feel free to work on it though if they'd like...
