### ISSUE TITLE
Support for inlining babel options

### ISSUE THREAD

**Issue by zamotany** [kentcdodds/babel-plugin-preval#33]
First of all, thanks for creating this amazing piece of work. I'm working on using this plugin for evaling css styles in tagged template literals on compile time, we have working prototype and we would like to give the users option to specify different babel config that will be used in evaling.

For instance, with webpack, currently the user cannot use `modules: false` with for instance `babel-preset-es2015` in `.babelrc`.

I'm happy to create and submit a PR to support this, but I need to know if you want to have it and collect some feedback before starting the work.

Here are the proposed additions:

### `preval` tagged template literal

A new function `preval.withOptions`, which would accept a stringified babel options, it would be then parsed with `JSON.parse`:

```js
const greeting = preval.withConfig('{"presets":["es2015"],"plugins":["myPlugin"]}')`
  const fs = require('fs')
  module.exports = fs.readFileSync(require.resolve('./greeting.txt'), 'utf8')
`
```

### import comment

A support for optional stringified babel options, after `preval` keyword:

```js
import fileList from /* preval {"presets":["es2015"],"plugins":["myPlugin"]} */ './get-list-of-files'
```

This way, it would still be possible to pass arguments:

```js
import fileList from /* preval(3) {"presets":["es2015"],"plugins":["myPlugin"]} */ './get-list-of-files'
```

### `preval.require`

Either accept a option as an object (or string) as a second argument:

```js
const fileLastModifiedDate = preval.require('./get-last-modified-date', { presets: ['es2015'] });
```

or expose a new function `requireWithOptions`, which would accept a 2nd argument:

```js
const fileLastModifiedDate = preval.requireWithOptions('./get-last-modified-date', { presets: ['es2015'] });
```

### preval file comment 

A support for stringified babel options after `preval` keyword:

```js
// @preval {"presets":["es2015"],"plugins":["myPlugin"]}

const id = require("./path/identity")
const one = require("./path/one")

const compose = (...fns) => fns.reduce((f, g) => a => f(g(a)))
const double = a => a * 2
const square = a => a * a

module.exports = compose(square, id, double)(one)
```

What do you think? Do you like it or not (please comment why) or do you have a better idea/solution?

Like I said, I'm happy to prepare a PR for this.

**Comment by satya164** [comment]
cc @kentcdodds

**Comment by kentcdodds** [comment]
Seems fine to me. I like the examples you have, except for `preval.require`, I'd prefer:

```javascript
const fileLastModifiedDate = preval.withConfig({ presets: ['es2015'] }).require('./get-last-modified-date');
```

That would apply to the tag. I wouldn't want it in a string. A normal object would be better:

```javascript
const greeting = preval.withConfig({"presets":["es2015"],"plugins":["myPlugin"]})`
  const fs = require('fs')
  module.exports = fs.readFileSync(require.resolve('./greeting.txt'), 'utf8')
`
```

Happy to accept a PR for this that documents it well and doesn't make everything terribly complicated :) Thanks!
