### ISSUE TITLE
Issue with JSPM and SystemJS

### ISSUE THREAD

**Issue by ArmorDarks** [kentcdodds/babel-plugin-preval#37]
- `babel-plugin-preval` version: `v1.5.0`
- `JSPM` version: `0.17.0-beta-42`

### What you did:

Installed prevel with JSPM:

```shell
jspm install preval=npm:babel-plugin-preval --dev
```

### What happened:

It resulted in error

```
err  Error on translate for kotsu/main.js at file:///J:/Work/Kotsu/github/source/scripts/main.js
  (SystemJS) ENOENT: no such file or directory, open 'J:\Work\Kotsu\github\${path.node.source.value}'
  Error: ENOENT: no such file or directory, open 'J:\Work\Kotsu\github\${path.node.source.value}'
  Error loading J:/Work/Kotsu/github/${path.node.source.value} as "${path.node.source.value}" from J:/Work/Kotsu/github/jspm_packages/npm/babel-plugin-preval@1.4.2/dist/index.js
```

### Problem description:

It seems that preval doesn't work well with JSPM and SystemJS.

In this issue https://github.com/jspm/jspm-cli/issues/2335 described few issues, that arises when prevel used with JSPM. Usually babel plugins working out of box with JSPM or SystemJS, but not in this case.

Most of described issues aren't that critical and workaroundable (though, it still a mystery to me are they caused by prevel or JSPM), except the last one, related to inability of JSPM locate a file (see error above).

### Suggested solution:

The source of the issue seems to be this line https://github.com/kentcdodds/babel-plugin-preval/blob/de16d3802e644e33c1df98d4f7d364b6bda61bb5/src/index.js#L87 with pseudo-template literal:

```js
'${path.node.source.value}'
```

Seems like JSPM is unable to handle it because to SystemJS it just another string, not a template literal.

**Comment by kentcdodds** [comment]
Hi @ArmorDarks,

Thanks for the issue and for digging a bit. I'm sorry but I have no idea how to solve this issue, and your suggested solution is actually just more of an explanation of the problem :wink:

If you think of something to do here (or anyone else does), feel free to mention it here and we can talk about what a PR to fix this would look like.

**Comment by ArmorDarks** [comment]
> If you think of something to do here

Unfortunately I don't :( If I'd know, I'd already post PR with a fix to SystemJS or prevel...

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this. Anyone can feel free to reopen if they have something actionable :+1:

**Comment by ArmorDarks** [comment]
Ouch, that hurts...
