### ISSUE TITLE
Video on Twitch seems to be no longer available

### ISSUE THREAD

**Issue by ArmorDarks** [kentcdodds/babel-plugin-preval#39]
Hi

Seems that mentioned in readme video about creating preval on Twitch no longer available 😞

**Comment by kentcdodds** [comment]
Thanks for letting me know! Here's the recording! https://www.youtube.com/watch?v=3vxov5xUai8&index=19&list=PLV5CVI1eNcJh5CTgArGVwANebCrAh2OUE
