### ISSUE TITLE
Refactor away babel-core dependency

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/babel-plugin-preval#43]
Due to https://github.com/kentcdodds/babel-macros/issues/41 we want to refactor `babel-core` away from our dependencies:

1. Remove `babel-core` from the package.json `dependencies`.
2. Remove the [require here](https://github.com/kentcdodds/babel-plugin-preval/blob/master/src/get-replacement.js) and instead accept `babel`  as a item in the options argument.
3. Change [this](https://github.com/kentcdodds/babel-plugin-preval/blob/master/src/index.js#L8) to babel and move the destructuring to a `const` on the next line.
4. Pass babel to each use of `getReplacement`

I think that's it. Anyone wanna do that?

**Comment by xjlim** [comment]
I'd like to work on this.

**Comment by kentcdodds** [comment]
Awesome. Thanks @xjlim!
