### ISSUE TITLE
Babel 7 support

### ISSUE THREAD

**Issue by oliviertassinari** [kentcdodds/babel-plugin-preval#52]
[Babel 7 is slowly rolling out](https://npm-stat.com/charts.html?package=babel-core&package=%40babel%2Fcore). At some point, it would be great to add support for it.

**Comment by oliviertassinari** [comment]
I believe we will need to upgrade the dependencies
https://github.com/kentcdodds/babel-plugin-preval/blob/b6eeba02ee93d425cc673ffc23dc62375d0416e5/package.json#L30-L32

**Comment by kentcdodds** [comment]
Sounds good. I'd be happy to accept a pull request for that 👍

**Comment by oliviertassinari** [comment]
I have been lazy. I have managed to use Babel 7 by [monkey patching some part of this plugin](https://github.com/mui-org/material-ui/pull/10964/files#diff-f9ab8f229a5aa32db0f68aaeddd6e5cdR2). Basically, it was all about:
```diff
-babel-registry
+@babel/registry
```

**Comment by tleunen** [comment]
@oliviertassinari is there anything else to do than just updating the version?

**Comment by oliviertassinari** [comment]
It's straightforward.
