### ISSUE TITLE
Closure context lost

### ISSUE THREAD

**Issue by linonetwo** [kentcdodds/babel-plugin-preval#53]
If there is:

```javascript
import preval from 'babel-plugin-preval/macro';

module.exports = preval`
  const _ = require('lodash');
  const arr = ['1', '2', '3'];

  module.exports = _.zipObject(arr, arr.map(variableName => loader => loader.load(variableName)));
`;
```

The imported 1 will be ```loader => loader.load(variableName)```
Where variableName is a missing variable, will throw an error ```variableName is not defined```

Even ```variableName => loader => loader.load(\`\${variableName}\`))``` is not working.
Then imported 1 will be ```loader => loader.load(`${variableName}`)```

**Comment by kentcdodds** [comment]
Yes, this is expected. There's no way to avoid this. You might consider [`codegen.macro`](https://www.npmjs.com/package/codegen.macro) for this use case instead.

Good luck!
