### ISSUE TITLE
How do you accept arguments

### ISSUE THREAD

**Issue by alex4o** [kentcdodds/babel-plugin-preval#56]
In the README.md you showed that it is possible to pass arguments to preval, is this possible, and how it works?

```js
import fileList from /* preval(3) */ './get-list-of-files'
```

**Comment by kentcdodds** [comment]
Maybe this will help:

https://www.youtube.com/watch?v=1queadQ0048&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u
