### ISSUE TITLE
Broken with @babel/preset-env

### ISSUE THREAD

**Issue by goodmind** [kentcdodds/babel-plugin-preval#58]
- `babel-plugin-preval` version: 2.0.0
- `node` version: 10.4.0
- `yarn` version: 1.7.0

Relevant code or config

```js
// file.js
module.exports = new RegExp("aaa", "gim");
```
```javascript
preval.require('./file.js')
```
```javascript
[
  "@babel/preset-env",
  {
    useBuiltIns: "usage",
    shippedProposals: true,
    modules: false,
    targets: {
      browsers: ["last 2 versions"]
    }
  }
]
```

What happened:

![image](https://user-images.githubusercontent.com/3275424/41897262-408041b4-7940-11e8-937b-6c47e5ce1a6e.png)

Reproduction repository: https://github.com/goodmind/preval-preset-env

Problem description: `@babel/preset-env` `useBuiltIns: "usage"` injects unnecessary polyfills

Suggested solution: none

**Comment by kentcdodds** [comment]
I'm seriously considering not transpiling code that is prevaled. It's causing a lot of problems and unexpected behavior for me as well. It's a handy feature, but I don't think it's worth it. I'll probably have this changed in the next day or two.

**Comment by kentcdodds** [comment]
This should be fixed.
