### ISSUE TITLE
run without babel (webpack)

### ISSUE THREAD

**Issue by no-more** [kentcdodds/babel-plugin-preval#60]
Hello,

This project looks amazing !
I was wondering if it could be used without babel.
I'm currently using webpack and trying to implement angular AOT. But this include some limitations that this project could solve.
But I need to preval only before aot is run and no other transformation. That's why I don't need babel process.

Thanks

**Comment by kentcdodds** [comment]
See the README where it references https://github.com/webpack-contrib/val-loader

I hope that helps.

**Comment by no-more** [comment]
Thanks for your response,

But sadly val-loader does not provide the same type of integration. It does not allow code to be replaced inline. It's focused on processing specific file only.
preval is much more convenient and allow more possibilities thanks to the inline replacement.

**Comment by kentcdodds** [comment]
Sorry, I don't think you can do this without Babel
