### ISSUE TITLE
[Suggestion] Implicit `module.exports ` if not specified

### ISSUE THREAD

**Issue by jhpratt** [kentcdodds/babel-plugin-preval#62]
I think implicitly adding `module.exports = ` at the beginning of a string where it's not specified would go a long ways towards reducing verbosity.

A possible solution would simple to be check if `/module\.exports\w*=/` is present in the string provided. It wouldn't catch all cases, but it also wouldn't introduce any false positives.

**Comment by kentcdodds** [comment]
Hi @jhpratt. Thanks for the suggestion, but I'd really prefer to limit the amount of magic from this plugin to reduce confusion.

Thanks anyway!
