### ISSUE TITLE
[Question] How to use --experimental-modules node mjs module

### ISSUE THREAD

**Issue by rockmandash** [kentcdodds/babel-plugin-preval#63]
Thank you for this wonderful library.
I have code need to preval, but they are written in es6 module
Needs to be executed with `--experimental-modules` arguments.
Can preval handle this? (I just try, it didn't work).
Without preval, I have to configure my project like this:
```json
{
  "build": "node --experimental-modules src/main.mjs && react-scripts build"
}
```
Which is also acceptable, but if preval supports it, it will be alot convinent.

Thank you for listening.

**Comment by kentcdodds** [comment]
I don't know honestly. If you can figure out a way to make it work then you can add something to the README, but it's not something I'm going to actively work on so I'll close this. Thanks.

**Comment by mryechkin** [comment]
@rockmandash sorry to bring up this old issue - I'm curious if you ever ended up solving this? I'm just trying out this plugin for the first time, and running into the same problem.
