### ISSUE TITLE
Cannot do typeof preval

### ISSUE THREAD

**Issue by feimosi** [kentcdodds/babel-plugin-preval#65]
- `babel-plugin-preval` version: 3.0.1
- `node` version: 11.10.1
- `yarn` version: 1.15.0

Relevant code or config

```javascript
typeof preval === 'function' ? preval` \* *\ ` : {};
```

What you did: Run `typeof` against `preval` function.

What happened: Failed with the following error:
`Error: babel-plugin-preval/macro: babel-plugin-preval/macro can only be used as tagged template expression, function call or JSX element. You tried UnaryExpression.`

Reproduction repository: N/A

Problem description:

I had problems with preval on the SSR server (related to importing the package) so I just wanted to run it conditionally on the client side, however I can't do `typeof` to check if it exists.

Suggested solution:

I think preval is being overprotective and too limiting while it should let the language itself validate what operations are valid.

I found this logic here:
https://github.com/kentcdodds/babel-plugin-preval/blob/d8be253f074ac9272a16ac88978da0ff25da8445/src/macro.js#L24-L30

**Comment by kentcdodds** [comment]
Sorry, but I don't think that code even makes sense considering preval is a compile-time thing that should never not exist. It's not a runtime thing at all.

**Comment by feimosi** [comment]
I don't understand your point, it is runtime if you run it on node. There's no compilation phase on the server-side. The code makes total sense and I don't see a reason to forbid such operations. `preval` is just a function after all.

**Comment by kentcdodds** [comment]
That's incorrect. This package is only intended to be run at compile time (it's a babel plugin) whether your code ends up running in the browser or node.
