### ISSUE TITLE
Not possible to mock implementation of preval in tests

### ISSUE THREAD

**Issue by gauthierm** [kentcdodds/babel-plugin-preval#68]
- `babel-plugin-preval` version: 3.0.1
- `node` version: 10.15.3
- `npm` (or `yarn`) version: 1.13.0

*Relevant code or config*:

```javascript
import React from 'react';
import { shallow } from 'enzyme';
import { BuildInfo } from './BuildInfo';
import preval from 'preval.macro';

jest.mock('preval.macro');

describe('<BuildInfo />', () => {
  test('renders successfully', () => {
    preval.mockImplementation(jest.fn().mockReturnValueOnce('ABC234'));
    const component = shallow(<BuildInfo />);
    expect(component).toMatchSnapshot();
  });
});
```

**What you did:**
Ran above test with jest.

**What happened:**

>  preval.macro: babel-plugin-preval/macro can only be used as tagged template expression, function call or JSX element. You tried MemberExpression. Learn more: https://www.npmjs.com/package/preval.macro

**Problem description:**

It's not possible to mock preval for snapshot tests. In my case, preval returns the current git commit hash which is not usable for snapshot tests.

**Suggested solution:**

It looks like extra code is in place to restrict how the function is called. Suggested solution is to update that to allow mocking preval in jest or other test frameworks.

**Comment by kentcdodds** [comment]
I'm afraid there's not really anything we can do in this package for you. The compilation happens before the mocking can take place. What I'd recommend is put the code that interacts with preval into a module which you mock.

An alternative would be to remove babel-plugin-macros from your babel config for tests and then mock `preval.macro`, but I think that could make things even more confusing if you wanted to have other macros that actually *do* run in your tests.

I hope that helps. Good luck.
