### ISSUE TITLE
suggestion - rename to just 'preval'

### ISSUE THREAD

**Issue by threepointone** [kentcdodds/babel-plugin-preval#7]
the `babel-plugin-` prefix is mostly inertia from the rest of the ecosystem, and creates dissonance especially when used with babel-macros. just `preval` would be nice, I think? the module name is available too, so do consider.

**Comment by kentcdodds** [comment]
As soon as the `babel-macros` API is solidified, then I'm happy to break free of the "inertia"
Until then, using `babel-plugin-` has the benefit of being what people expect :wink:

**Comment by kentcdodds** [comment]
Oh, and when `babel-macros` is solidified, then I'll probably remove the normal plugin altogether and _just_ allow for the macros.

**Comment by kentcdodds** [comment]
Based on conversations in `babel-macros`, I think the API is fairly solid. What do you think @threepointone, should I just rename this to `preval` and require people to use `babel-macros`? 😱

**Comment by kentcdodds** [comment]
Going to leave this as-is because a lot of folks are using `preval` as a babel plugin and I don't think that'll change. If someone wants to use [`preval.macro`](https://www.npmjs.com/package/preval.macro) then they're more than welcome (and encouraged) to do so.
