### ISSUE TITLE
Ignoring preval in node_modules

### ISSUE THREAD

**Issue by codejamninja** [kentcdodds/babel-plugin-preval#72]
I have a node_module with preval in it, but this is ignoring it. It only works when preval is used outside of `node_modules`.

**Comment by kentcdodds** [comment]
Hi @codejamninja,

This is nothing that we can do within this plugin. If you want packages in your `node_modules` to be compiled with babel, you'll need to configure babel to do that. Here's more info: https://babeljs.io/docs/en/config-files

Good luck!

**Comment by littlee** [comment]
Will enabling this plugin arises potential security issue ? It looks like anybody can run a piece of node program inside a npm package.

**Comment by kentcdodds** [comment]
It should only run at build-time and should never room in production.
