### ISSUE TITLE
Does not work via Node API

### ISSUE THREAD

**Issue by akidee** [kentcdodds/babel-plugin-preval#92]
- `@babel/core` 7.13.14
- `babel-plugin-preval` version: 5.0.0
- `node` version: v14.10.1
- `npm` version: 6.14.8

Relevant code or config

```javascript
const code = `
const v = 1 + 2
module.exports = { v }
`

console.log(require('@babel/core').transformSync(code, {
  plugins: ['preval']
}).code)
```

What you did:

I'd like to use preval at runtime to optimize some functions in a longer running script.
For, this, I installed babel and preval as normal dependencies and ran the script above:

```
$ npm install --save @babel/core @babel/preset-env babel-plugin-preval
$ node prevaltest.js
const v = 1 + 2;
module.exports = {
  v
};
```
What happened:

The script has not been transformed as expected.

**Comment by kentcdodds** [comment]
Your `code` isn't using preval. It only transforms code that follows the API in the README.

I think it's more likely you want something like this: https://github.com/floatdrop/require-from-string

**Comment by akidee** [comment]
I am still looking for a working version of prepack (which is not stable and discontinued).

How can I use preval directly? I use old style modules, and `require('babel-plugin-preval/macro').preval` is `undefined`. I have configured babel-plugin-macros in `babel.config.js`:

```javascript
const plugins = [ 'preval' ]
, presets = [];

module.exports = function (api) {
	api.cache(false);
	return { plugins, presets };
}
```
