### ISSUE TITLE
[Request] - Mention a plugin interaction

### ISSUE THREAD

**Issue by MrcSnm** [kentcdodds/babel-plugin-preval#94]
Hello!
I've made some plugin for webpack that generates a C-Like macro. So, I've been using this plugin with babel-plugin-preval, and it has a great relationship with this plugin.

For instance, I could define a new macro called _FILENAME_NO_EXT: which would write the current filename without any extension. 

```ts
DEFINE(_FILENAME_NO_EXT, () =>
{
   return preval`__filename.substring(__filename.lastIndexOf("/")+1, __filename.lastIndexOf("."))`
});
```

When this function is called anywhere, the output code would be the filename where this function is called, every compile time feature has much to gain from that as it is a simple text replace tool.

//index.ts

console.log(_FILENAME_NO_EXT()); //index

Hope you take a look and we could work in some more interactions for [define_macro-loader](https://www.npmjs.com/package/@hipreme_entertainment/define_macro-loader)

**Comment by kentcdodds** [comment]
Cool! Feel free to make a PR to the bottom of the README under "Related Projects" to mention your project 👍

**Comment by MrcSnm** [comment]
Thanks a lot for the appreciation!
