### ISSUE TITLE
add support for preval comments

### ISSUE THREAD

**Issue by ForgottenR** [kentcdodds/babel-plugin-preval#98]
There currently is no support to preval comments, which might be a useful approach to manage comment hints provided by other plugins.
I understand this project may have been frozen or something, but it would be nice to at least have some discussion in case someone forked it or want to start a new project similar to it.

**Comment by kentcdodds** [comment]
Hi @lcdlyxrqy!
I'm afraid that's outside the scope of this package. However you should be able to do that with the sister package: babel-plugin-codegen 😁
